// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: itemsaver_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url     string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Id      string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Type    string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Profile *Profile `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itemsaver_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_itemsaver_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_itemsaver_message_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type Profile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Gender     string  `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Age        uint32  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Height     float32 `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	Weight     float32 `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Income     string  `protobuf:"bytes,6,opt,name=income,proto3" json:"income,omitempty"`
	Marriage   string  `protobuf:"bytes,7,opt,name=marriage,proto3" json:"marriage,omitempty"`
	Education  string  `protobuf:"bytes,8,opt,name=education,proto3" json:"education,omitempty"`
	Occupation string  `protobuf:"bytes,9,opt,name=occupation,proto3" json:"occupation,omitempty"`
	HuKou      string  `protobuf:"bytes,10,opt,name=huKou,proto3" json:"huKou,omitempty"`
	XinZuo     string  `protobuf:"bytes,11,opt,name=xinZuo,proto3" json:"xinZuo,omitempty"`
	House      string  `protobuf:"bytes,12,opt,name=house,proto3" json:"house,omitempty"`
	Car        string  `protobuf:"bytes,13,opt,name=car,proto3" json:"car,omitempty"`
	CommonInfo string  `protobuf:"bytes,14,opt,name=commonInfo,proto3" json:"commonInfo,omitempty"`
}

func (x *Profile) Reset() {
	*x = Profile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itemsaver_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_itemsaver_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_itemsaver_message_proto_rawDescGZIP(), []int{1}
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Profile) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Profile) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Profile) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Profile) GetIncome() string {
	if x != nil {
		return x.Income
	}
	return ""
}

func (x *Profile) GetMarriage() string {
	if x != nil {
		return x.Marriage
	}
	return ""
}

func (x *Profile) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *Profile) GetOccupation() string {
	if x != nil {
		return x.Occupation
	}
	return ""
}

func (x *Profile) GetHuKou() string {
	if x != nil {
		return x.HuKou
	}
	return ""
}

func (x *Profile) GetXinZuo() string {
	if x != nil {
		return x.XinZuo
	}
	return ""
}

func (x *Profile) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *Profile) GetCar() string {
	if x != nil {
		return x.Car
	}
	return ""
}

func (x *Profile) GetCommonInfo() string {
	if x != nil {
		return x.CommonInfo
	}
	return ""
}

var File_itemsaver_message_proto protoreflect.FileDescriptor

var file_itemsaver_message_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x61, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x63, 0x72, 0x61, 0x77, 0x6c,
	0x65, 0x72, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2e, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x61, 0x76, 0x65, 0x72, 0x22, 0x7e, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65,
	0x72, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2e, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x61, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52,
	0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0xdf, 0x02, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61,
	0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61,
	0x72, 0x72, 0x69, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61,
	0x72, 0x72, 0x69, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x63, 0x63, 0x75, 0x70, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x75, 0x4b, 0x6f, 0x75, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x75, 0x4b, 0x6f, 0x75, 0x12, 0x16, 0x0a, 0x06, 0x78, 0x69,
	0x6e, 0x5a, 0x75, 0x6f, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x78, 0x69, 0x6e, 0x5a,
	0x75, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x61, 0x72, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x61, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x18, 0x5a, 0x16, 0x63, 0x72,
	0x61, 0x77, 0x6c, 0x65, 0x72, 0x2d, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_itemsaver_message_proto_rawDescOnce sync.Once
	file_itemsaver_message_proto_rawDescData = file_itemsaver_message_proto_rawDesc
)

func file_itemsaver_message_proto_rawDescGZIP() []byte {
	file_itemsaver_message_proto_rawDescOnce.Do(func() {
		file_itemsaver_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_itemsaver_message_proto_rawDescData)
	})
	return file_itemsaver_message_proto_rawDescData
}

var file_itemsaver_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_itemsaver_message_proto_goTypes = []interface{}{
	(*Item)(nil),    // 0: crawler.distributed.itemsaver.Item
	(*Profile)(nil), // 1: crawler.distributed.itemsaver.Profile
}
var file_itemsaver_message_proto_depIdxs = []int32{
	1, // 0: crawler.distributed.itemsaver.Item.profile:type_name -> crawler.distributed.itemsaver.Profile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_itemsaver_message_proto_init() }
func file_itemsaver_message_proto_init() {
	if File_itemsaver_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_itemsaver_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itemsaver_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Profile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_itemsaver_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_itemsaver_message_proto_goTypes,
		DependencyIndexes: file_itemsaver_message_proto_depIdxs,
		MessageInfos:      file_itemsaver_message_proto_msgTypes,
	}.Build()
	File_itemsaver_message_proto = out.File
	file_itemsaver_message_proto_rawDesc = nil
	file_itemsaver_message_proto_goTypes = nil
	file_itemsaver_message_proto_depIdxs = nil
}
