// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: itemsaver_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemSaverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *ItemSaverRequest) Reset() {
	*x = ItemSaverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itemsaver_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemSaverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSaverRequest) ProtoMessage() {}

func (x *ItemSaverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_itemsaver_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSaverRequest.ProtoReflect.Descriptor instead.
func (*ItemSaverRequest) Descriptor() ([]byte, []int) {
	return file_itemsaver_service_proto_rawDescGZIP(), []int{0}
}

func (x *ItemSaverRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type ItemSaverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ItemSaverResponse) Reset() {
	*x = ItemSaverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_itemsaver_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemSaverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSaverResponse) ProtoMessage() {}

func (x *ItemSaverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_itemsaver_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSaverResponse.ProtoReflect.Descriptor instead.
func (*ItemSaverResponse) Descriptor() ([]byte, []int) {
	return file_itemsaver_service_proto_rawDescGZIP(), []int{1}
}

func (x *ItemSaverResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_itemsaver_service_proto protoreflect.FileDescriptor

var file_itemsaver_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x61, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x63, 0x72, 0x61, 0x77, 0x6c,
	0x65, 0x72, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2e, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x61, 0x76, 0x65, 0x72, 0x1a, 0x17, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x61,
	0x76, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4b, 0x0a, 0x10, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x61, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x61,
	0x76, 0x65, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x25,
	0x0a, 0x11, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x61, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x7f, 0x0a, 0x10, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x61, 0x76,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6b, 0x0a, 0x04, 0x53, 0x61, 0x76,
	0x65, 0x12, 0x2f, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x61, 0x76, 0x65,
	0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x61, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x30, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x61, 0x76,
	0x65, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x61, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x18, 0x5a, 0x16, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65,
	0x72, 0x2d, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_itemsaver_service_proto_rawDescOnce sync.Once
	file_itemsaver_service_proto_rawDescData = file_itemsaver_service_proto_rawDesc
)

func file_itemsaver_service_proto_rawDescGZIP() []byte {
	file_itemsaver_service_proto_rawDescOnce.Do(func() {
		file_itemsaver_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_itemsaver_service_proto_rawDescData)
	})
	return file_itemsaver_service_proto_rawDescData
}

var file_itemsaver_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_itemsaver_service_proto_goTypes = []interface{}{
	(*ItemSaverRequest)(nil),  // 0: crawler.distributed.itemsaver.ItemSaverRequest
	(*ItemSaverResponse)(nil), // 1: crawler.distributed.itemsaver.ItemSaverResponse
	(*Item)(nil),              // 2: crawler.distributed.itemsaver.Item
}
var file_itemsaver_service_proto_depIdxs = []int32{
	2, // 0: crawler.distributed.itemsaver.ItemSaverRequest.item:type_name -> crawler.distributed.itemsaver.Item
	0, // 1: crawler.distributed.itemsaver.ItemSaverService.Save:input_type -> crawler.distributed.itemsaver.ItemSaverRequest
	1, // 2: crawler.distributed.itemsaver.ItemSaverService.Save:output_type -> crawler.distributed.itemsaver.ItemSaverResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_itemsaver_service_proto_init() }
func file_itemsaver_service_proto_init() {
	if File_itemsaver_service_proto != nil {
		return
	}
	file_itemsaver_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_itemsaver_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemSaverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_itemsaver_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemSaverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_itemsaver_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_itemsaver_service_proto_goTypes,
		DependencyIndexes: file_itemsaver_service_proto_depIdxs,
		MessageInfos:      file_itemsaver_service_proto_msgTypes,
	}.Build()
	File_itemsaver_service_proto = out.File
	file_itemsaver_service_proto_rawDesc = nil
	file_itemsaver_service_proto_goTypes = nil
	file_itemsaver_service_proto_depIdxs = nil
}
