// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: worker_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SerializedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string      `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Parser *ParserFunc `protobuf:"bytes,2,opt,name=parser,proto3" json:"parser,omitempty"`
}

func (x *SerializedRequest) Reset() {
	*x = SerializedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerializedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedRequest) ProtoMessage() {}

func (x *SerializedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedRequest.ProtoReflect.Descriptor instead.
func (*SerializedRequest) Descriptor() ([]byte, []int) {
	return file_worker_message_proto_rawDescGZIP(), []int{0}
}

func (x *SerializedRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SerializedRequest) GetParser() *ParserFunc {
	if x != nil {
		return x.Parser
	}
	return nil
}

type ParserFunc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionName string `protobuf:"bytes,1,opt,name=functionName,proto3" json:"functionName,omitempty"`
	Args         string `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *ParserFunc) Reset() {
	*x = ParserFunc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParserFunc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParserFunc) ProtoMessage() {}

func (x *ParserFunc) ProtoReflect() protoreflect.Message {
	mi := &file_worker_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParserFunc.ProtoReflect.Descriptor instead.
func (*ParserFunc) Descriptor() ([]byte, []int) {
	return file_worker_message_proto_rawDescGZIP(), []int{1}
}

func (x *ParserFunc) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *ParserFunc) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type SerializedParserResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items   []*Item              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Request []*SerializedRequest `protobuf:"bytes,2,rep,name=request,proto3" json:"request,omitempty"`
}

func (x *SerializedParserResult) Reset() {
	*x = SerializedParserResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_worker_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SerializedParserResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerializedParserResult) ProtoMessage() {}

func (x *SerializedParserResult) ProtoReflect() protoreflect.Message {
	mi := &file_worker_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerializedParserResult.ProtoReflect.Descriptor instead.
func (*SerializedParserResult) Descriptor() ([]byte, []int) {
	return file_worker_message_proto_rawDescGZIP(), []int{2}
}

func (x *SerializedParserResult) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SerializedParserResult) GetRequest() []*SerializedRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

var File_worker_message_proto protoreflect.FileDescriptor

var file_worker_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x1a, 0x17, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x61, 0x76, 0x65, 0x72, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x11, 0x53,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x3e, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e,
	0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x46, 0x75, 0x6e, 0x63, 0x52, 0x06, 0x70, 0x61, 0x72, 0x73,
	0x65, 0x72, 0x22, 0x44, 0x0a, 0x0a, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x46, 0x75, 0x6e, 0x63,
	0x12, 0x22, 0x0a, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x16, 0x53, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x50, 0x61, 0x72, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x61, 0x76,
	0x65, 0x72, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x47,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x64, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x18, 0x5a, 0x16, 0x63, 0x72, 0x61, 0x77, 0x6c,
	0x65, 0x72, 0x2d, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_worker_message_proto_rawDescOnce sync.Once
	file_worker_message_proto_rawDescData = file_worker_message_proto_rawDesc
)

func file_worker_message_proto_rawDescGZIP() []byte {
	file_worker_message_proto_rawDescOnce.Do(func() {
		file_worker_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_worker_message_proto_rawDescData)
	})
	return file_worker_message_proto_rawDescData
}

var file_worker_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_worker_message_proto_goTypes = []interface{}{
	(*SerializedRequest)(nil),      // 0: crawler.distributed.worker.SerializedRequest
	(*ParserFunc)(nil),             // 1: crawler.distributed.worker.ParserFunc
	(*SerializedParserResult)(nil), // 2: crawler.distributed.worker.SerializedParserResult
	(*Item)(nil),                   // 3: crawler.distributed.itemsaver.Item
}
var file_worker_message_proto_depIdxs = []int32{
	1, // 0: crawler.distributed.worker.SerializedRequest.parser:type_name -> crawler.distributed.worker.ParserFunc
	3, // 1: crawler.distributed.worker.SerializedParserResult.items:type_name -> crawler.distributed.itemsaver.Item
	0, // 2: crawler.distributed.worker.SerializedParserResult.request:type_name -> crawler.distributed.worker.SerializedRequest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_worker_message_proto_init() }
func file_worker_message_proto_init() {
	if File_worker_message_proto != nil {
		return
	}
	file_itemsaver_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_worker_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerializedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParserFunc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_worker_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SerializedParserResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_worker_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_worker_message_proto_goTypes,
		DependencyIndexes: file_worker_message_proto_depIdxs,
		MessageInfos:      file_worker_message_proto_msgTypes,
	}.Build()
	File_worker_message_proto = out.File
	file_worker_message_proto_rawDesc = nil
	file_worker_message_proto_goTypes = nil
	file_worker_message_proto_depIdxs = nil
}
